# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2.xci
# IP: The module: 'system_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2.xci
# IP: The module: 'system_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/workspace/Vivado_2018.3/zcu104/fft2/fft2.srcs/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
