#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 09 00:02:32 +07 2019
# SW Build 2288692 on Thu Jul 26 18:23:50 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim test_pBlaze_behav -key {Behavioral:sim_1:Functional:test_pBlaze} -tclbatch test_pBlaze.tcl -view /home/esi/workspace/Vivado_2018.2/zcu104/fft/fft.sim/sim_1/test_pBlaze_behav.wcfg -log simulate.log
